SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SELECTALLZAHTJEVI]

AS

SELECT T1.KupacID, T1.Naslov,T1.ZahtjeviID,T1.Datum, T2.Ime AS Ime FROM Zahtjevi AS T1 inner join Kupci AS T2 ON T1.KupacID=T2.KupacID
ORDER BY T1.KupacID

GO
