//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEP_GameShop_Administracija {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class poruke {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal poruke() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PEP_GameShop_Administracija.poruke", typeof(poruke).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa je obavezna!.
        /// </summary>
        internal static string adresa_req {
            get {
                return ResourceManager.GetString("adresa_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa je obavezna!.
        /// </summary>
        internal static string adresad_req {
            get {
                return ResourceManager.GetString("adresad_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite broj racuna.
        /// </summary>
        internal static string brojracuna_req {
            get {
                return ResourceManager.GetString("brojracuna_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijena mora biti broj.
        /// </summary>
        internal static string cijena_broj {
            get {
                return ResourceManager.GetString("cijena_broj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijena je obavezna.
        /// </summary>
        internal static string cijena_req {
            get {
                return ResourceManager.GetString("cijena_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum ne može biti današnji niti manji od danjašnjeg.
        /// </summary>
        internal static string date_error {
            get {
                return ResourceManager.GetString("date_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobavljač je obavezan!.
        /// </summary>
        internal static string dobavljac_ob {
            get {
                return ResourceManager.GetString("dobavljac_ob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno dodan dobavljač!.
        /// </summary>
        internal static string dobavljac_succ {
            get {
                return ResourceManager.GetString("dobavljac_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.mail adresa je zauzeta!.
        /// </summary>
        internal static string email_con {
            get {
                return ResourceManager.GetString("email_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail nije unesen u ispravnom formatu!.
        /// </summary>
        internal static string email_error {
            get {
                return ResourceManager.GetString("email_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail je obavezan!.
        /// </summary>
        internal static string email_req {
            get {
                return ResourceManager.GetString("email_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email je obavezan!.
        /// </summary>
        internal static string emaild_req {
            get {
                return ResourceManager.GetString("emaild_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj fakture je obavezan!.
        /// </summary>
        internal static string faktura_req {
            get {
                return ResourceManager.GetString("faktura_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igre su obavezne!.
        /// </summary>
        internal static string igre_req {
            get {
                return ResourceManager.GetString("igre_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime je obavezno!.
        /// </summary>
        internal static string ime_error {
            get {
                return ResourceManager.GetString("ime_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izdavac je obavezan!.
        /// </summary>
        internal static string izdavac_req {
            get {
                return ResourceManager.GetString("izdavac_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno sačuvano.
        /// </summary>
        internal static string izlaz_succ {
            get {
                return ResourceManager.GetString("izlaz_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt osoba je obavezna!.
        /// </summary>
        internal static string kontakt_req {
            get {
                return ResourceManager.GetString("kontakt_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime je obavezno!.
        /// </summary>
        internal static string korisnickoime_error {
            get {
                return ResourceManager.GetString("korisnickoime_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali novog korisnika!.
        /// </summary>
        internal static string korisnikSuccessAdd {
            get {
                return ResourceManager.GetString("korisnikSuccessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niste unijeli ispravne podatke, molimo pokušajte ponovo&quot;.
        /// </summary>
        internal static string loginError {
            get {
                return ResourceManager.GetString("loginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste prijavljeni!.
        /// </summary>
        internal static string loginSuccess {
            get {
                return ResourceManager.GetString("loginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka mora biti duža od 5 karaktera!.
        /// </summary>
        internal static string lozinka_req {
            get {
                return ResourceManager.GetString("lozinka_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite narudžbu.
        /// </summary>
        internal static string narudzba_req {
            get {
                return ResourceManager.GetString("narudzba_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naslov je obavezan!.
        /// </summary>
        internal static string naslov_req {
            get {
                return ResourceManager.GetString("naslov_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv je obavezan!.
        /// </summary>
        internal static string naziv_req {
            get {
                return ResourceManager.GetString("naziv_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv je obavezan!.
        /// </summary>
        internal static string nazivd_req {
            get {
                return ResourceManager.GetString("nazivd_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis je obavezan!.
        /// </summary>
        internal static string opis_req {
            get {
                return ResourceManager.GetString("opis_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime je obavezno!.
        /// </summary>
        internal static string prezime_error {
            get {
                return ResourceManager.GetString("prezime_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno dodana recenzija.
        /// </summary>
        internal static string recenzija_success {
            get {
                return ResourceManager.GetString("recenzija_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadržaj je obavezan!.
        /// </summary>
        internal static string sadrzaj_req {
            get {
                return ResourceManager.GetString("sadrzaj_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra je obavezna!.
        /// </summary>
        internal static string sifra_req {
            get {
                return ResourceManager.GetString("sifra_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno dodano skladište!.
        /// </summary>
        internal static string sklad_succ {
            get {
                return ResourceManager.GetString("sklad_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skladište je obavezno!.
        /// </summary>
        internal static string skladiste_req {
            get {
                return ResourceManager.GetString("skladiste_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slika je obavezna.
        /// </summary>
        internal static string slika_req {
            get {
                return ResourceManager.GetString("slika_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije moguće promjenit status!.
        /// </summary>
        internal static string status_err {
            get {
                return ResourceManager.GetString("status_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste obrisali korisnika!.
        /// </summary>
        internal static string success_deletekorisnik {
            get {
                return ResourceManager.GetString("success_deletekorisnik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste deaktivirali korisnika!.
        /// </summary>
        internal static string success_korisnikdeaktiviran {
            get {
                return ResourceManager.GetString("success_korisnikdeaktiviran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon je obavezan!.
        /// </summary>
        internal static string telefon_error {
            get {
                return ResourceManager.GetString("telefon_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon je obavezan!.
        /// </summary>
        internal static string telefond_req {
            get {
                return ResourceManager.GetString("telefond_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite trailer u ispravnom formatu.
        /// </summary>
        internal static string trailer_req {
            get {
                return ResourceManager.GetString("trailer_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno sačuvano!.
        /// </summary>
        internal static string ulaz_succ {
            get {
                return ResourceManager.GetString("ulaz_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno sačuvano!.
        /// </summary>
        internal static string ulaz_succs {
            get {
                return ResourceManager.GetString("ulaz_succs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite uloge!.
        /// </summary>
        internal static string uloge_req {
            get {
                return ResourceManager.GetString("uloge_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno izmjenjeni lični podatci!.
        /// </summary>
        internal static string update_succ {
            get {
                return ResourceManager.GetString("update_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promjene uspješno sačuvane!.
        /// </summary>
        internal static string update_success {
            get {
                return ResourceManager.GetString("update_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime je zauzeto!.
        /// </summary>
        internal static string username_con {
            get {
                return ResourceManager.GetString("username_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrsta je obavezna.
        /// </summary>
        internal static string vrsta_req {
            get {
                return ResourceManager.GetString("vrsta_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žiro račun je obavezan!.
        /// </summary>
        internal static string ziro_req {
            get {
                return ResourceManager.GetString("ziro_req", resourceCulture);
            }
        }
    }
}
