//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Data
{
    using System;
    
    public partial class AukcijeBYKupac_Result1
    {
        public int AukcijeID { get; set; }
        public int KorisnikID { get; set; }
        public System.DateTime DatumDO { get; set; }
        public System.DateTime DatumOD { get; set; }
        public Nullable<int> IgraID { get; set; }
        public string Naziv { get; set; }
        public decimal Ponuda { get; set; }
        public Nullable<System.DateTime> DatumPonude { get; set; }
    }
}
