//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Igre
    {
        public Igre()
        {
            this.IzlazStavke = new HashSet<IzlazStavke>();
            this.NarudzbeStavke = new HashSet<NarudzbeStavke>();
            this.Ocjene = new HashSet<Ocjene>();
            this.UlazStavke = new HashSet<UlazStavke>();
            this.Recenzije = new HashSet<Recenzije>();
            this.Aukcije = new HashSet<Aukcije>();
        }
    
        public int IgraID { get; set; }
        public string Naziv { get; set; }
        public string DatumIzdavanja { get; set; }
        public int IzdavacID { get; set; }
        public decimal Cijena { get; set; }
        public byte[] Slika { get; set; }
        public string Trailer { get; set; }
        public string Opis { get; set; }
        public int VrstaID { get; set; }
        public byte[] SlikaThumb { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Šifra { get; set; }
        public Nullable<bool> Aukcija { get; set; }
    
        public virtual Izdavaci Izdavaci { get; set; }
        public virtual Vrsta Vrsta { get; set; }
        public virtual ICollection<IzlazStavke> IzlazStavke { get; set; }
        public virtual ICollection<NarudzbeStavke> NarudzbeStavke { get; set; }
        public virtual ICollection<Ocjene> Ocjene { get; set; }
        public virtual ICollection<UlazStavke> UlazStavke { get; set; }
        public virtual ICollection<Recenzije> Recenzije { get; set; }
        public virtual ICollection<Aukcije> Aukcije { get; set; }
    }
}
