//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kupci
    {
        public Kupci()
        {
            this.Izlazi = new HashSet<Izlazi>();
            this.Narudzbe = new HashSet<Narudzbe>();
            this.Ocjene = new HashSet<Ocjene>();
            this.Zahtjevi = new HashSet<Zahtjevi>();
            this.ZahtjeviKupci = new HashSet<ZahtjeviKupci>();
        }
    
        public int KupacID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public System.DateTime DatumRegistracije { get; set; }
        public string Email { get; set; }
        public string KorisnickoIme { get; set; }
        public string LozinkaHash { get; set; }
        public string LozinkaSalt { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<Izlazi> Izlazi { get; set; }
        public virtual ICollection<Narudzbe> Narudzbe { get; set; }
        public virtual ICollection<Ocjene> Ocjene { get; set; }
        public virtual ICollection<Zahtjevi> Zahtjevi { get; set; }
        public virtual ICollection<ZahtjeviKupci> ZahtjeviKupci { get; set; }
    }
}
