//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZahtjeviKupci
    {
        public int ZahtjeviKupciID { get; set; }
        public int KupacID { get; set; }
        public int ZahtjevID { get; set; }
    
        public virtual Kupci Kupci { get; set; }
        public virtual Zahtjevi Zahtjevi { get; set; }
    }
}
